version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: stoik/api:nestjs9
    depends_on:
      database:
        condition: service_healthy
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_NAME}
    networks:
      - app
  database:
    image: postgres
    container_name: database
    restart: always
    networks:
      - app
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: true
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_HOST: ${DATABASE_HOST}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DATABASE_USERNAME}",
          "-d",
          "${DATABASE_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 50
  server:
    image: nginx:stable-alpine
    container_name: stoik-nginx
    depends_on:
      - api
    restart: always
    networks:
      - app
    volumes:
      - ./confignginx:/etc/nginx/templates
    ports:
      - 8080:80

networks:
  app:
